### ISSUE TITLE
Error trying activate user Calendar

### ISSUE THREAD

**Issue by BoGnY** [mantisbt-plugins/Calendar#16]
Hi, I have follow all step for installation, but when I'm on user calendar page, I click on "Enable sync with Google Calendar", I allow permission, but at the end, I give this error:
> The server denied the request. 
> Error: Could not determine client ID from request

The strange thing is that the redirect uri after oauth permission is this: https://bug.bogny.eu/plugin.php?page=Calendar/user_config_google&state=%5B%22user_config_google%22%5D&code=4/AAA7m0ynV3KTzmkYzn_rBE5N39-AXpxK5IUbQDphxh60tp8je46c-RKXM4TqPfY0hCThz1LWS4moAxSBNHhDrOE#

Maybe the problem are caused by **%5B%22** or **%22%5D**????? IDK

This is my uploaded json file:

```json
                                    Array
(
    [client_id] => 1234567890-ASDASDASDASDASDASD.apps.googleusercontent.com
    [project_id] => bogny-eu
    [auth_uri] => https://accounts.google.com/o/oauth2/auth
    [token_uri] => https://accounts.google.com/o/oauth2/token
    [auth_provider_x509_cert_url] => https://www.googleapis.com/oauth2/v1/certs
    [redirect_uris] => Array
        (
            [0] => https://bug.bogny.eu/plugin.php?page=Calendar/user_config_google
        )
    [javascript_origins] => Array
        (
            [0] => https://bug.bogny.eu
        )
)
```
Thanks for any help!

**Comment by brlumen** [comment]
Hello @BoGnY!
I will try to help you as quickly as possible!

**Comment by brlumen** [comment]
@BoGnY
I deleted the line "client_secret" from my json file and the error was reproduced exactly like you.
So try again download the file from the google control panel.

**Comment by BoGnY** [comment]
Sorry, now it works... Maybe a server problem 👍
