### ISSUE TITLE
Incorrect integer value: '' for column 'date_changed' at row 1 

### ISSUE THREAD

**Issue by azkoss** [mantisbt-plugins/Calendar#22]
APPLICATION ERROR #401

数据库查询失败。数据库返回的错误信息是：#1366: Incorrect integer value: '' for column 'date_changed' at row 1 查询语句：INSERT INTO mantis_plugin_Calendar_events_table
( project_id, name,
activity, author_id, date_changed,
changed_user_id, date_from, date_to,
duration, recurrence_pattern, parent_id
)
VALUES
( ?,?,
?,?,?,
?,?,?,
?,?,?)

**Comment by brlumen** [comment]
@azkoss Hello! 
What version of MantisBT do you use?

**Comment by azkoss** [comment]
MantisBT版本 | 2.15.0
Calendar of Events 2.4.4-dev

**Comment by azkoss** [comment]
@brlumen 

MantisBT版本 | 2.15.0
Calendar of Events 2.4.4-dev

**Comment by brlumen** [comment]
@azkoss This error when installing the plug-in for the first time or when updating the plug-in?

**Comment by azkoss** [comment]
@brlumen First installation

**Comment by brlumen** [comment]
@azkoss Thanks for the info!
One more question.
Could you provide information from the page you_mantisbt/manage_overview_page.php

**Comment by azkoss** [comment]
MantisBT版本 | 2.15.0
-- | --
209
 
5.6.33
mysqli
5.5.37, 5.5.37-log
 
/var/www/html/
/var/www/html/core/
/var/www/html/plugins/

**Comment by brlumen** [comment]
@azkoss Many thanks for the bug message and the detailed description of the configuration. I'll immediately take care of playing back your configuration and searching for the cause of this bug.

**Comment by azkoss** [comment]
@brlumen When to fix it?

**Comment by brlumen** [comment]
@azkoss Please download now.
I really look forward to your feedback.

**Comment by brlumen** [comment]
@azkoss Please describe the sequence of your actions before this error occurs.

**Comment by azkoss** [comment]
@brlumen 

1、Open Event Viewer;2)Click Edit Button,Open Changing event details;3)Click Edit Data Button

**Comment by brlumen** [comment]
@azkoss 
Is this the first event you created?
Try to create another event and update it.

**Comment by azkoss** [comment]
@brlumen Even then, they still happen.

**Comment by brlumen** [comment]
@azkoss Good. In that case, tomorrow I'll try to reproduce the error in a similar way to your configuration.
I apologize for the negative experience in using my plugin.
I will direct all resources to eliminate this problem.

**Comment by brlumen** [comment]
Сontinue the discussion in issue #23
