### ISSUE TITLE
Are you sure you want to delete this event? SYSTEM ERROR

### ISSUE THREAD

**Issue by azkoss** [mantisbt-plugins/Calendar#23]
SYSTEM ERROR

'Argument 1 passed to event_google_get_id() must be an instance of int, integer given, called in /var/www/html/plugins/Calendar/core/calendar_google_api.php on line 216 and defined' in '/var/www/html/plugins/Calendar/core/calendar_google_api.php' line 248

**Comment by brlumen** [comment]
@azkoss 
I fixed the bug.
Check, please.

**Comment by azkoss** [comment]
@brlumen 

Fixed

Thanks!
