### ISSUE TITLE
Calendar Fatal error: Call to undefined function print_column_time()

### ISSUE THREAD

**Issue by georgelmk** [mantisbt-plugins/Calendar#30]
I'm facing a problem with Calendar plugin.
After the installation of the plugin i am getting [Fatal error: Call to undefined function print_column_time() ]
plugins\Calendar\pages\calendar_user_page.php on line 99

MantisBT Version: 2.18.0

Any help with this issue??

**Comment by brlumen** [comment]
@georgelmk 
Hello! Today I will definitely test with mantisbt 2.18.0.
It is not clear for what reason this error occurs.

**Comment by georgelmk** [comment]
Hello!
thanks for your response!
i will be waiting for your results after the tests!

**Comment by brlumen** [comment]
@georgelmk Could you please provide information from the "manage_overview_page.php" page?

**Comment by brlumen** [comment]
@georgelmk 
I can not reproduce this error. Please provide additional information.

**Comment by georgelmk** [comment]
MantisBT Version 	2.18.0
Schema Version 	209
PHP Version 	5.6.25
Database Driver 	mysqli
Database Version, Description 	5.7.14, 5.7.14
Site Path 	C:\wamp\www\mantisbt\
Core Path 	C:\wamp\www\mantisbt\core\
Plugin Path 	C:\wamp\www\mantisbt\plugins\

**Comment by georgelmk** [comment]
MantisBT Version 	2.18.0
Schema Version 	209
PHP Version 	5.6.25
Database Driver 	mysqli
Database Version, Description 	5.7.14, 5.7.14

**Comment by brlumen** [comment]
Eureka!
The mistake was in one feature related to microsoft systems.
Case-insensitive file system.
One of the files with the desired function was named the same as the file in the mantisbt itself, only with a capital letter.

Patch on the way. I think that by the evening the new version will already be available. I need to correct a few more nuances.

**Comment by brlumen** [comment]
Since the changes affected a significant part of the code base, testing took longer than I thought.
I'll try to post a patch tomorrow.

**Comment by georgelmk** [comment]
hello
Bravo for the immediate solution!
i will test the plugin next days.

thanks
