### ISSUE TITLE
The server denied the request.  Error: Invalid code

### ISSUE THREAD

**Issue by 1800548** [mantisbt-plugins/Calendar#32]
Hello, I meet error when I doing step 12 (sync google calendar).
I input: 'http://YOU_DOMAIN_HOSTED_MANTISBT/plugin.php?page=Calendar/user_config_google', but it say can't redirect.

In addition, can Calendar plugins combine with Reminder plugins?
Thank you!
![default](https://user-images.githubusercontent.com/47883955/53230877-aa495a00-36c2-11e9-94ea-b19deaf6b97c.png)
![u](https://user-images.githubusercontent.com/47883955/53230878-aa495a00-36c2-11e9-8a8b-fec808db0dc5.png)

**Comment by brlumen** [comment]
@1800548 Hello!
In the line with the address you use "http", and Google requires "https".

**Comment by brlumen** [comment]
>In addition, can Calendar plugins combine with Reminder plugins?

Unfortunately not. In any case, this functionality will have to be implemented together with the developer of the Reminder-plugin.

**Comment by 1800548** [comment]
@brlumen 
Thank you for your reply!

I try to redirect the address from "http" to "https" before, but I don't have establish certificate for my mantis website, is this the reason why I can't use it?
Moreover, can you tell me what this URL "https://..../user_config_google" using for ?

BR

**Comment by brlumen** [comment]
@1800548 
>I try to redirect the address from "http" to "https" before, but I don't have establish certificate for my mantis website, is this the reason why I can't use it?

Yes. Google requires that the link be via https and that the certificate is trusted and not self-signed.

>Moreover, can you tell me what this URL "https://..../user_config_google" using for ?

If I understand your question correctly, this link is used to redirect the user from the Google access confirmation page to his calendar, back to the Mantisbt calendar configuration page.
After the user clicks "allow" access to his calendar in Google, Google will redirect the user to the page "https: //..../user_config_google".

**Comment by brlumen** [comment]
@1800548 
In addition to the redirect itself, Google returns a unique key identifier, which is later used for authorization in the process of synchronizing calendars. Unfortunately, except from this link it does not get it.

**Comment by 1800548** [comment]
@brlumen 

OK!
My question is over,
Thank you for your patience in answering my question!

**Comment by brlumen** [comment]
It's my pleasure!
