### ISSUE TITLE
Problems with installation

### ISSUE THREAD

**Issue by jjproe** [mantisbt-plugins/Calendar#40]
Hello !

i trying to install Calendar Plugin v 2.6 on mantis v 2.23.0 / shema version 210 / postgres  v11.4.
On the Adminview - Plugins it means i need a Updgrade (required mantis v 2.14).

By pressing Upgrade it shows an ERROR #2503 in Block #0 .

Whats wrong ? I activated logging, but cant see nothing.. 
And Calendar is not working.

Thanks !

**Comment by brlumen** [comment]
Hello @jjproe !
Most likely the fact is that you are using postgres. I have already encountered such a problem in my other plugin. I will try to release a patch this weekend.

**Comment by brlumen** [comment]
@jjproe , please download and install this path https://github.com/brlumen/Calendar/archive/fix-issue-pgsql.zip

**Comment by brlumen** [comment]
#41
