### ISSUE TITLE
A MultiProject Calendar 

### ISSUE THREAD

**Issue by msansen-esncf** [mantisbt-plugins/Calendar#42]
Hi,

First, thanks for the plugin!

Possible to add choise ,in settings, if we want one calendar per project or one calendar for every projects?
To be able to add to the same event differents bugs for differents projects (they are linked and must be done at the same event)

Many Thanks
Regards

Mat

**Comment by brlumen** [comment]
Hi Mat!

This is possible if the projects have a common parent and a new event is
created in the project parent.  If this condition is fulfilled, a list of
issue of all children's projects will be available to you.

If you have more questions, I will be happy to answer them.

вт, 31 мар. 2020 г., 17:22 msansen-esncf <notifications@github.com>:

**Comment by msansen-esncf** [comment]
hi,

thanks for your answer, i've done it as explained and it works fine.

Regards

Mat
