### ISSUE TITLE
Calander not displaying correctly

### ISSUE THREAD

**Issue by bamburyl** [mantisbt-plugins/Calendar#44]
![image](https://user-images.githubusercontent.com/74960951/100078801-d23b9380-2e3b-11eb-875b-9059b433d306.png)

I have installed the calendar using the installation guide, but it is not showing as the images with the events in boxes and times and dates.   We are not linking this to google would this cause an issue?

Calendar of Events 2.6.0 is the version being used
MantisBT Core 2.24.2

Thanks

**Comment by brlumen** [comment]
Hello!
I checked it on a clean installation - the bug you described did not appear.
Could you describe your configuration in more detail?
Also, please send the error output from the browser console. In google chrome it can be called via Ctrl-Shift-i> "console" tab.

**Comment by bamburyl** [comment]
Hi sorry for the late reply,  was looking into the error assuming something is wrong with the plugin file.

![image](https://user-images.githubusercontent.com/74960951/100612702-4af29200-330b-11eb-95bf-7b7ee302d550.png)

**Comment by brlumen** [comment]
@bamburyl 
It is not clear where the "<" error appears.

Please send the "Page Code" (CTRL + U). It is advisable to save it to a file beforehand.

Thanks!

**Comment by bamburyl** [comment]
[Calander.txt](https://github.com/mantisbt-plugins/Calendar/files/5622643/Calander.txt)
The attached file, hopefully, what you wanted :)

**Comment by brlumen** [comment]
@bamburyl , the code is fine.

Maybe some browser extension is interfering?
Does the page have display errors in incognito mode?

**Comment by bamburyl** [comment]
No not extension sn incognito will not even work for mantis on my machine any way just shows blank wont even load.  I have removed the extension for now.
