### ISSUE TITLE
Errors when trying to install plugin

### ISSUE THREAD

**Issue by bamburyl** [mantisbt-plugins/Calendar#45]
We have done a new clean install of mantis bt but using MS SQL server this time.  But when trying to install the calender we get the following errors.

APPLICATION ERROR #2503

Upgrading the plugin schema failed at step #4. Error "SQLState: 42000
Error Code: 156
Message: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near the keyword 'DROP'.
SQLState: 42000
Error Code: 102
Message: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near 'date_event'.
SQLState: 42000
Error Code: 102
Message: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near 'hour_start'.
SQLState: 42000
Error Code: 102
Message: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near 'minutes_start'.
SQLState: 42000
Error Code: 102
Message: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near 'hour_finish'.
SQLState: 42000
Error Code: 102
Message: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near 'minutes_finish'.
" occurred while executing the following statement(s):
ALTER TABLE mantis_plugin_Calendar_events_table DROP COLUMN tasks, DROP COLUMN date_event, DROP COLUMN hour_start, DROP COLUMN minutes_start, DROP COLUMN hour_finish, DROP COLUMN minutes_finish

Please use the "Back" button in your web browser to return to the previous page. There you can correct whatever problems were identified in this error or select another action. You can also click an option from the menu bar to go directly to a new section.

Version Info
![image](https://user-images.githubusercontent.com/74960951/101514997-c987a900-3975-11eb-9654-624526cc97c2.png)

**Comment by brlumen** [comment]
Hello! Please try this version https://github.com/brlumen/Calendar/archive/fix-issue-pgsql.zip
