### ISSUE TITLE
Clicking 'Current week' button takes user to previous week

### ISSUE THREAD

**Issue by priocomdevops** [mantisbt-plugins/Calendar#47]
When I click on 'Current week' button, it takes me to the previous week instead of the actual current week.

**Comment by m0vida** [comment]
Also have the same issue here.

**Comment by Zipher04** [comment]
The calendar_user_page also show the previous week in default. I have to click the next button to show current week.

**Comment by brlumen** [comment]
I will try to fix it next week.
