### ISSUE TITLE
Send outlook ical event once add event in Calendar plugin

### ISSUE THREAD

**Issue by sintaq83** [mantisbt-plugins/Calendar#49]
Hi,

Is there a way to send outlook ical event once added event in Calendar plugin ?

**Comment by brlumen** [comment]
Hey! There is no such function at the moment. But you can use the integration with google.

**Comment by sintaq83** [comment]
Hi @brlumen 
Any plan in the pipeline? Can it be request?

**Comment by sintaq83** [comment]
@brlumen 
Am closing this as am able to address the topic by local customization. Thanks for the plugin!
