### ISSUE TITLE
Event Viewer

### ISSUE THREAD

**Issue by rmorenocampos** [mantisbt-plugins/Calendar#51]
Hello,
It seems that when I open the Event Viewer of an event already scheduled in the calendar, the following Warning message appears on the 'update_bug_button' and 'delete_bug_button' buttons:
`APPLICATION WARNING #300: String "update_bug_button" not found. (in '/var/www/html/plugins/Calendar/pages/view.php' line 100)`
`APPLICATION WARNING #300: String "delete_bug_button" not found. (in '/var/www/html/plugins/Calendar/pages/view.php' line 101)`

Why is this? It seems that the buttons are not loading correctly, or if these are the buttons, how can I remove the Warning messages?

Thanks in advance!

**Comment by brlumen** [comment]
I'll see what could be the issue.
This notification appears when display of warning-level mantisbt events is
enabled. If it is acceptable, then turn off the display of errors in the
mantisbt config file.

ср, 18 мая 2022 г., 15:11 rmorenocampos ***@***.***>:
