### ISSUE TITLE
DEPRECATED: 'Return type of RRule\RRule::next() should either be compatible with Iterator::next(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice

### ISSUE THREAD

**Issue by hannes7g** [mantisbt-plugins/Calendar#53]
Hi Thanks for the plugin. But i am getting errors at every page after i have installed it. Do you know how to remove this error? Because i cant click on the View Issues button for example, probably because the error list is very long.
Thank you.

PHP 8.1.12
Mantis 2.25.5
Calendar 2.6.1

DEPRECATED: 'Return type of RRule\RRule::next() should either be compatible with Iterator::next(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice' in 'D:\nginx\html\mantisbt\plugins\Calendar\api\php-rrule-1.6.1\src\RRule.php' line 1033
DEPRECATED: 'Return type of RRule\RRule::key() should either be compatible with Iterator::key(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice' in 'D:\nginx\html\mantisbt\plugins\Calendar\api\php-rrule-1.6.1\src\RRule.php' line 1025
DEPRECATED: 'Return type of RRule\RRule::valid() should either be compatible with Iterator::valid(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice' in 'D:\nginx\html\mantisbt\plugins\Calendar\api\php-rrule-1.6.1\src\RRule.php' line 1042
DEPRECATED: 'Return type of RRule\RRule::rewind() should either be compatible with Iterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice' in 'D:\nginx\html\mantisbt\plugins\Calendar\api\php-rrule-1.6.1\src\RRule.php' line 1008
DEPRECATED: 'Return type of RRule\RRule::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice' in 'D:\nginx\html\mantisbt\plugins\Calendar\api\php-rrule-1.6.1\src\RRule.php' line 1053
DEPRECATED: 'Return type of RRule\RRule::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice' in 'D:\nginx\html\mantisbt\plugins\Calendar\api\php-rrule-1.6.1\src\RRule.php' line 1061
DEPRECATED: 'Return type of RRule\RRule::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice' in 'D:\nginx\html\mantisbt\plugins\Calendar\api\php-rrule-1.6.1\src\RRule.php' line 1093

**Comment by brlumen** [comment]
Hello! Please enter your version mantisbt, php and database.

пн, 20 февр. 2023 г., 22:06 hannes7g ***@***.***>:

**Comment by hannes7g** [comment]
Hi I solved it by changing php.ini 
FROM error_reporting = E_ALL
TO error_reporting = E_ALL & ~E_NOTICE & ~E_DEPRECATED

btw i already wrote it in the message. between logs and my description of the error. 

I guess somebody needs to take care of this before the next versions of php disable these api calls completely.

**Comment by hannes7g** [comment]
I think we can close this issue.
