### ISSUE TITLE
Cant add users to an event

### ISSUE THREAD

**Issue by hannes7g** [mantisbt-plugins/Calendar#55]
![image](https://user-images.githubusercontent.com/89947792/220159005-fa0b62be-71ba-4f0c-821f-dba4b4395841.png)

PHP 8.1.12
Mantis 2.25.5
Calendar 2.6.1

**Comment by brlumen** [comment]
Check the current project. The list will contain users who have access to
the selected project.

пн, 20 февр. 2023 г., 23:28 hannes7g ***@***.***>:
